# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff1faa6ad523030c9f1f0b3b5cfd999f7bbf304c9f5a6b315a2d9be817479793346532cdd62e83e993262afa2c98d88b60f104190f5df6b2ca6a9fa651f43fbb

test:
  secret_key_base: d84eb0fe120c78f4e02e5b65ab2cfeca9f004ecd3f81f3887f0078a9c2607b58fa6dd92c0240e4898299e35c1bad39c9f4d78dab143e80b948d03ddfe9f3671b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
